language: rust
cache: cargo

rust:
  - 1.28.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - env HAZPTR_SCAN_FREQ=1 cargo test --test integration --features  "count-release"
# - cargo build --no-default-features --verbose
# - cargo test --no-default-features --verbose

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

