language: rust
cache: cargo

rust:
  - 1.34.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
 
