language: rust
cache: cargo

rust:
  - 1.36.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --test integration --features  "count-release maximum-reclamation-freq"

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

