language: rust
cache: cargo

rust:
  - 1.26.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --test integration --features  "count-release maximum-reclamation-freq"
# - cargo build --no-default-features --verbose
# - cargo test --no-default-features --verbose

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

